# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - none

pool:
  vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      jobs:
          - job: 'Job_Build'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world.'

    - stage: Test
      jobs:
          - job: 'Job_Test'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'

    - stage: Deploy
      pool: server
      jobs:
          - job: 'Job_Deploy'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'
            - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
              inputs:
                connectedServiceName: 'emprpolanki4-DevOpsADOProject4-ServiceNow DevOps Service Connection'
                artifactsPayload: |
                  {
                      "artifacts": [
                        {
                            "name": "msnautomation-agent-registration-artifact.jar",
                            "version": "1.$(Build.BuildId)",
                            "semanticVersion": "1.$(Build.BuildId).0",
                            "repositoryName": "MSNAutomation"
                        }
                      ]
                  }            
            - task: ServiceNow-DevOps-Server-Change-Acceleration@1
              inputs:
                connectedServiceName: 'emprpolanki4-DevOpsADOProject4-ServiceNow DevOps Service Connection'
                UpstreamJob: 'Job_Test'
                changeRequestDetails: |
                  {
                      "setCloseCode" : true,
                      "attributes": {
                        "requested_by": {
                          "name": "devops.system"
                        },
                        "start_date": "2021-09-26 08:00:00",
                        "end_date": "2021-09-28 08:00:00"
                      }
                    }