# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - none

pool:
  vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      jobs:
          - job: 'Job_Build'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world.'

    - stage: Test
      jobs:
          - job: 'Job_Test'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'

    - stage: Deploy
      jobs:
          - job: 'Job_Deploy'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'
            - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
              inputs:
                connectedServiceName: 'emprpolanki4-DevOpsADOProject4-ServiceNow DevOps Service Connection'
                artifactsPayload: |
                  {
                      "artifacts": [
                        {
                            "name": "msnautomation-agent-registration-artifact.jar",
                            "version": "1.$(Build.BuildId)",
                            "semanticVersion": "1.$(Build.BuildId).0",
                            "repositoryName": "MSNAutomation"
                        }
                      ]
                  }            

    - stage: Prod
      jobs:
          - job: 'Job_Prod'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'