stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Build' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Build_Job' #Job name cannot have spaces
    displayName: 'Application Build' #Name displayed when viewing in Azure DevOps
    pool:
      vmImage: 'windows-latest' #See available agent images: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        SourceFolder: $(system.defaultworkingdirectory)
        Contents: '**/*.jar'
        TargetFolder: $(build.artifactstagingdirectory)   

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)    

- stage: 'Test_Stage' #Stage name cannot have spaces
  displayName: 'Test' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Test_Job' #Job name cannot have spaces
    displayName: 'Application Test' #Name displayed when viewing in Azure DevOps
    steps:
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testResultsFiles: '**/TEST-*.xml'
        searchFolder: $(System.DefaultWorkingDirectory)
